#define PI_FLOAT ((float)M_PI)
// TODO: make sure in debugger that these represent inifinities
#define POSITIVE_INFINITY_FLOAT ((float)(1e308 * 10))
#define NEGATIVE_INFINITY_FLOAT ((float)(-1e308 * 10))
//#define POSITIVE_INFINITY_FLOAT (+(INFINITY))
//#define NEGATIVE_INFINITY_FLOAT (-(INFINITY))
#define QUIET_NAN_FLOAT (NAN)
#define MAX_VALUE_UINT (UINT_MAX)
#define FLOAT_MIN (-FLT_MAX)
#define FLOAT_MAX (FLT_MAX)
